### ISSUE TITLE
can't run docker-compose build

### ISSUE THREAD

**Issue by yasahmed** [kuldeepsingh99/microservice-consul#1]
i get this error : 
```

mongo uses an image, skipping
consul uses an image, skipping
Building gateway
ERROR: Cannot locate specified Dockerfile: Dockerfile
```

**Comment by kuldeepsingh99** [comment]
Are you running the docker-compose command from micro project ?

**Comment by yasahmed** [comment]
im sorry, it was my mistake i should rename my DockerFile -> Dockerfile because im using windows, but i have another issue in consul dashboard i don't see order service and i can't get access to geteway on port  8600

**Comment by kuldeepsingh99** [comment]
Please check for correct ports, it should work
